### ISSUE TITLE
fastroute should gracefully die on illegal macro placement

### ISSUE THREAD

**Issue by tajayi** [The-OpenROAD-Project/FastRoute#9]
**Priority:** Medium

**Details:**
There is currently a bug in fplan that can result in macros being placed outside of the design area or on top of each other. This results in a mysterious crash by fastroute. The tool should be able to detect this bad behavior and gracefully die

**Comment by oharboe** [comment]
I would change "gracefully die" to be more specific: "produce a helpful error message"

**Comment by isadorasop** [comment]
Please, check commit 4aa46b16e85b5a628497ac1e6d3784a4f786c6cf.

**Comment by tajayi** [comment]
Validated

```

----------------
Checking pin placement...
Checking pin placement... Done!
Checking macros...
ERROR: There are macros outside the die area.
ERROR: There are macros outside the die area.
ERROR: There are macros outside the die area.
ERROR: There are macros outside the die area.
ERROR: There are macros outside the die area.
ERROR: There are macros that overlap eachother.
ERROR: There are macros that overlap eachother.
ERROR: There are macros that overlap eachother.
ERROR: There are macros that overlap eachother.
ERROR: There are macros that overlap eachother.
ERROR: There are macros that overlap eachother.
ERROR: There are macros that overlap eachother.
ERROR: There are macros that overlap eachother.
ERROR: There are macros that overlap eachother.
make: *** [results/tsmc65lp/bp_fe_top/route.guide] Error 254
make: Leaving directory `/net/trenton/x/ajayi/projects/OpenROAD/alpha-release/flow'

**Comment by tajayi** [comment]
Ooops... Looks like it fails to check "valid" floorplans
![image](https://user-images.githubusercontent.com/1457793/63101541-3daf6980-bf47-11e9-89fa-eea16ec6ec11.png)

```
Checking pin placement...
Checking pin placement... Done!
Checking macros...
ERROR: There are macros outside the die area.
ERROR: There are macros that overlap eachother.
make: *** [results/tsmc65lp/bsg_manycore_tile/route.guide] Error 254
make: Leaving directory `/net/trenton/x/ajayi/projects/OpenROAD/alpha-release/flow'
```

My suspicion is that the math may not comprehend rotations. All of the macros in the design above are rotated R90.

PS, if it's easy to print the exact macro name that's violating, that might be helpful

**Comment by oharboe** [comment]
could the makefile flow write out this picture to results/?

tor. 15. aug. 2019, 16:29 skrev Tutu Ajayi <notifications@github.com>:

**Comment by tajayi** [comment]
The image is generated using a commercial tool/software. Long term, I plan to integrate klayout to generate similar pictures and will probably put them in the results folder.

**Comment by oharboe** [comment]
gotit.


a bit of bling in reporting goes a long way. i would urge reporting to be
compatible w continuous integration: static files with no gui. perhaps a
top level html file?

tor. 15. aug. 2019, 17:30 skrev Tutu Ajayi <notifications@github.com>:

**Comment by vvbandeira** [comment]
@tajayi, can you test with the new version on the master branch (dd29747029fe0e4837da8696153998d5dd91aa89)?

Thanks for your feedback.

**Comment by tajayi** [comment]
Closing this for now

**Comment by eder-matheus** [comment]
FastRoute generates warning messages for any object out of the die area, pointing the name of the instances with this issue. No segfault with the available testcases
